# Generated by Django 5.2.11 on 2026-03-24 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
